packages:
  - 'apps/*'
  - 'packages/*'
catalogs:
  electron:
    electron: 43.0.0-beta.3
  'electron-builder':
    'electron-builder': 26.0.11
  prisma:
    prisma: 7.8.0
  '@prisma/client':
    '@prisma/client': 7.8.0
  '@prisma/driver-adapter-utils':
    '@prisma/driver-adapter-utils': 7.8.0
  vite:
    vite: 8.0.16
