// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'c520cae73ca9578fbf5df58a7a64e8d2aa782a70b02130cd15c869fd6abf455c'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Account: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'];
      readonly email: CodecTypes['sqlite/text@1']['output'] | null;
      readonly globalSetting: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly Thread: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly accountId: CodecTypes['sqlite/text@1']['output'];
      readonly setting: CodecTypes['sqlite/text@1']['output'] | null;
      readonly chatProvider: CodecTypes['sqlite/text@1']['output'] | null;
      readonly chatModel: CodecTypes['sqlite/text@1']['output'] | null;
      readonly vectorTag: CodecTypes['sqlite/text@1']['output'] | null;
      readonly vectorSearchMode: CodecTypes['sqlite/text@1']['output'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['output'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['output'];
    };
    readonly ThreadMessage: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly accountId: CodecTypes['sqlite/text@1']['output'];
      readonly threadId: CodecTypes['sqlite/text@1']['output'];
      readonly chatProvider: CodecTypes['sqlite/text@1']['output'];
      readonly chatModel: CodecTypes['sqlite/text@1']['output'];
      readonly prompt: CodecTypes['sqlite/text@1']['output'];
      readonly promptId: CodecTypes['sqlite/text@1']['output'];
      readonly response: CodecTypes['sqlite/text@1']['output'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['output'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Account: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'];
      readonly email: CodecTypes['sqlite/text@1']['input'] | null;
      readonly globalSetting: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly Thread: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly accountId: CodecTypes['sqlite/text@1']['input'];
      readonly setting: CodecTypes['sqlite/text@1']['input'] | null;
      readonly chatProvider: CodecTypes['sqlite/text@1']['input'] | null;
      readonly chatModel: CodecTypes['sqlite/text@1']['input'] | null;
      readonly vectorTag: CodecTypes['sqlite/text@1']['input'] | null;
      readonly vectorSearchMode: CodecTypes['sqlite/text@1']['input'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['input'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['input'];
    };
    readonly ThreadMessage: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly accountId: CodecTypes['sqlite/text@1']['input'];
      readonly threadId: CodecTypes['sqlite/text@1']['input'];
      readonly chatProvider: CodecTypes['sqlite/text@1']['input'];
      readonly chatModel: CodecTypes['sqlite/text@1']['input'];
      readonly prompt: CodecTypes['sqlite/text@1']['input'];
      readonly promptId: CodecTypes['sqlite/text@1']['input'];
      readonly response: CodecTypes['sqlite/text@1']['input'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['input'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly Account: {
      readonly email: CodecTypes['sqlite/text@1']['output'] | null;
      readonly globalSetting: CodecTypes['sqlite/text@1']['output'] | null;
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly username: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Thread: {
      readonly accountId: CodecTypes['sqlite/text@1']['output'];
      readonly chatModel: CodecTypes['sqlite/text@1']['output'] | null;
      readonly chatProvider: CodecTypes['sqlite/text@1']['output'] | null;
      readonly createTime: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly setting: CodecTypes['sqlite/text@1']['output'] | null;
      readonly updateTime: CodecTypes['sqlite/datetime@1']['output'];
      readonly vectorSearchMode: CodecTypes['sqlite/text@1']['output'];
      readonly vectorTag: CodecTypes['sqlite/text@1']['output'] | null;
    };
    readonly ThreadMessage: {
      readonly accountId: CodecTypes['sqlite/text@1']['output'];
      readonly chatModel: CodecTypes['sqlite/text@1']['output'];
      readonly chatProvider: CodecTypes['sqlite/text@1']['output'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly prompt: CodecTypes['sqlite/text@1']['output'];
      readonly promptId: CodecTypes['sqlite/text@1']['output'];
      readonly response: CodecTypes['sqlite/text@1']['output'];
      readonly threadId: CodecTypes['sqlite/text@1']['output'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly Account: {
      readonly email: CodecTypes['sqlite/text@1']['input'] | null;
      readonly globalSetting: CodecTypes['sqlite/text@1']['input'] | null;
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly username: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Thread: {
      readonly accountId: CodecTypes['sqlite/text@1']['input'];
      readonly chatModel: CodecTypes['sqlite/text@1']['input'] | null;
      readonly chatProvider: CodecTypes['sqlite/text@1']['input'] | null;
      readonly createTime: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly setting: CodecTypes['sqlite/text@1']['input'] | null;
      readonly updateTime: CodecTypes['sqlite/datetime@1']['input'];
      readonly vectorSearchMode: CodecTypes['sqlite/text@1']['input'];
      readonly vectorTag: CodecTypes['sqlite/text@1']['input'] | null;
    };
    readonly ThreadMessage: {
      readonly accountId: CodecTypes['sqlite/text@1']['input'];
      readonly chatModel: CodecTypes['sqlite/text@1']['input'];
      readonly chatProvider: CodecTypes['sqlite/text@1']['input'];
      readonly createTime: CodecTypes['sqlite/datetime@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly prompt: CodecTypes['sqlite/text@1']['input'];
      readonly promptId: CodecTypes['sqlite/text@1']['input'];
      readonly response: CodecTypes['sqlite/text@1']['input'];
      readonly threadId: CodecTypes['sqlite/text@1']['input'];
      readonly updateTime: CodecTypes['sqlite/datetime@1']['input'];
    };
  };
};

export namespace Models {
  export type Account = {
    id: CodecTypes['sqlite/text@1']['output'];
    username: CodecTypes['sqlite/text@1']['output'];
    email: CodecTypes['sqlite/text@1']['output'] | null;
    globalSetting: CodecTypes['sqlite/text@1']['output'] | null;
    threads: Thread[];
    threadMessages: ThreadMessage[];
    readonly [RelationKeys]?: 'threads' | 'threadMessages';
  };
  export type Thread = {
    id: CodecTypes['sqlite/text@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'];
    accountId: CodecTypes['sqlite/text@1']['output'];
    setting: CodecTypes['sqlite/text@1']['output'] | null;
    chatProvider: CodecTypes['sqlite/text@1']['output'] | null;
    chatModel: CodecTypes['sqlite/text@1']['output'] | null;
    vectorTag: CodecTypes['sqlite/text@1']['output'] | null;
    vectorSearchMode: CodecTypes['sqlite/text@1']['output'];
    updateTime: CodecTypes['sqlite/datetime@1']['output'];
    createTime: CodecTypes['sqlite/datetime@1']['output'];
    account: Account;
    readonly [RelationKeys]?: 'account';
  };
  export type ThreadMessage = {
    id: CodecTypes['sqlite/text@1']['output'];
    accountId: CodecTypes['sqlite/text@1']['output'];
    threadId: CodecTypes['sqlite/text@1']['output'];
    chatProvider: CodecTypes['sqlite/text@1']['output'];
    chatModel: CodecTypes['sqlite/text@1']['output'];
    prompt: CodecTypes['sqlite/text@1']['output'];
    promptId: CodecTypes['sqlite/text@1']['output'];
    response: CodecTypes['sqlite/text@1']['output'];
    updateTime: CodecTypes['sqlite/datetime@1']['output'];
    createTime: CodecTypes['sqlite/datetime@1']['output'];
    account: Account;
    readonly [RelationKeys]?: 'account';
  };
}

export declare const models: {
  Account: Models.Account;
  Thread: Models.Thread;
  ThreadMessage: Models.ThreadMessage;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly Account: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'uuid()'>;
                  };
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly globalSetting: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['username'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Thread: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'uuid()'>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly setting: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly chatProvider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly chatModel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly vectorTag: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly vectorSearchMode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'default'>;
                  };
                };
                readonly updateTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/datetime@1', 'now()'>;
                  };
                };
                readonly createTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/datetime@1', 'now()'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Thread_accountId_idx_cbfb3085';
                  readonly prefix: 'Thread_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Thread';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Account';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly ThreadMessage: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', 'uuid()'>;
                  };
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly threadId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly chatProvider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', ''>;
                  };
                };
                readonly chatModel: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', ''>;
                  };
                };
                readonly prompt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly promptId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly response: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly updateTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/datetime@1', 'now()'>;
                  };
                };
                readonly createTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/datetime@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/datetime@1', 'now()'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['promptId'] }];
              indexes: readonly [
                {
                  readonly name: 'ThreadMessage_accountId_idx_cbfb3085';
                  readonly prefix: 'ThreadMessage_accountId_idx';
                  readonly columns: readonly ['accountId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'ThreadMessage';
                    readonly columns: readonly ['accountId'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'Account';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Account: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Account';
    };
    readonly Thread: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Thread' };
    readonly ThreadMessage: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ThreadMessage';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly globalSetting: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly threads: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Thread';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
              readonly threadMessages: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ThreadMessage';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['accountId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Account';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly username: { readonly column: 'username' };
                readonly email: { readonly column: 'email' };
                readonly globalSetting: { readonly column: 'globalSetting' };
              };
            };
          };
          readonly Thread: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly setting: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly chatProvider: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly chatModel: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly vectorTag: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly vectorSearchMode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updateTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly createTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Account';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Thread';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly accountId: { readonly column: 'accountId' };
                readonly setting: { readonly column: 'setting' };
                readonly chatProvider: { readonly column: 'chatProvider' };
                readonly chatModel: { readonly column: 'chatModel' };
                readonly vectorTag: { readonly column: 'vectorTag' };
                readonly vectorSearchMode: { readonly column: 'vectorSearchMode' };
                readonly updateTime: { readonly column: 'updateTime' };
                readonly createTime: { readonly column: 'createTime' };
              };
            };
          };
          readonly ThreadMessage: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly threadId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly chatProvider: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly chatModel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly prompt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly promptId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly response: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updateTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
              readonly createTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
              };
            };
            readonly relations: {
              readonly account: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Account';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['accountId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ThreadMessage';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly accountId: { readonly column: 'accountId' };
                readonly threadId: { readonly column: 'threadId' };
                readonly chatProvider: { readonly column: 'chatProvider' };
                readonly chatModel: { readonly column: 'chatModel' };
                readonly prompt: { readonly column: 'prompt' };
                readonly promptId: { readonly column: 'promptId' };
                readonly response: { readonly column: 'response' };
                readonly updateTime: { readonly column: 'updateTime' };
                readonly createTime: { readonly column: 'createTime' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
